services:
  mf_drawer:
    build: ./mf_drawer
    ports:
      - "8080:8080"
  mf_videos:
    build: ./mf_videos
    ports:
      - "8081:8081"
  bff:
    build: ./bff
    ports:
      - "3000:3000"
  main:
    build: ./main
    ports:
      - "8082:8082"